[customizations.installer.kickstart]
contents = """
text --non-interactive
zerombr
clearpart --all --initlabel --disklabel=gpt
reqpart --add-boot
part / --fstype=xfs --grow
bootloader --append="intel_iommu=on amd_iommu=on iommu=pt"
keyboard us
lang en_US.UTF-8
timezone UTC
rootpw --lock
user --name=almavirt --password=almavirt --plaintext --groups=wheel,libvirt
network --bootproto=dhcp --device=link --activate --onboot=on
poweroff --eject
%post --erroronfail
bootc switch --mutate-in-place --transport registry ghcr.io/yuanandcircle/almavirt:latest
%end
"""
